var searchData=
[
  ['data_192',['Data',['../union_data.html',1,'']]],
  ['dedupvtables_193',['DedupVtables',['../classflatbuffers_1_1_flat_buffer_builder.html#aa905b29dce19a1795c7bce375cf29961',1,'flatbuffers::FlatBufferBuilder::DedupVtables(bool dedup)'],['../classflatbuffers_1_1_flat_buffer_builder.html#aa905b29dce19a1795c7bce375cf29961',1,'flatbuffers::FlatBufferBuilder::DedupVtables(bool dedup)']]],
  ['defaultallocator_194',['DefaultAllocator',['../classflatbuffers_1_1_default_allocator.html',1,'flatbuffers']]],
  ['densifyoptionsbuilder_195',['DensifyOptionsBuilder',['../structtflite_1_1_densify_options_builder.html',1,'tflite']]],
  ['densifyoptionst_196',['DensifyOptionsT',['../structtflite_1_1_densify_options_t.html',1,'tflite']]],
  ['depthtospaceoptionsbuilder_197',['DepthToSpaceOptionsBuilder',['../structtflite_1_1_depth_to_space_options_builder.html',1,'tflite']]],
  ['depthtospaceoptionst_198',['DepthToSpaceOptionsT',['../structtflite_1_1_depth_to_space_options_t.html',1,'tflite']]],
  ['depthtospaceparams_199',['DepthToSpaceParams',['../structtflite_1_1_depth_to_space_params.html',1,'tflite']]],
  ['depthwiseconv2doptionsbuilder_200',['DepthwiseConv2DOptionsBuilder',['../structtflite_1_1_depthwise_conv2_d_options_builder.html',1,'tflite']]],
  ['depthwiseconv2doptionst_201',['DepthwiseConv2DOptionsT',['../structtflite_1_1_depthwise_conv2_d_options_t.html',1,'tflite']]],
  ['depthwiseconvbasickernel_202',['DepthwiseConvBasicKernel',['../structtflite_1_1reference__ops_1_1depthwise__conv_1_1_depthwise_conv_basic_kernel.html',1,'tflite::reference_ops::depthwise_conv']]],
  ['depthwiseparams_203',['DepthwiseParams',['../structtflite_1_1_depthwise_params.html',1,'tflite']]],
  ['dequantizationparams_204',['DequantizationParams',['../structtflite_1_1_dequantization_params.html',1,'tflite']]],
  ['dequantizeoptionsbuilder_205',['DequantizeOptionsBuilder',['../structtflite_1_1_dequantize_options_builder.html',1,'tflite']]],
  ['dequantizeoptionst_206',['DequantizeOptionsT',['../structtflite_1_1_dequantize_options_t.html',1,'tflite']]],
  ['detachedbuffer_207',['DetachedBuffer',['../classflatbuffers_1_1_detached_buffer.html',1,'flatbuffers']]],
  ['dimensionmetadatabuilder_208',['DimensionMetadataBuilder',['../structtflite_1_1_dimension_metadata_builder.html',1,'tflite']]],
  ['dimensionmetadatat_209',['DimensionMetadataT',['../structtflite_1_1_dimension_metadata_t.html',1,'tflite']]],
  ['dims_210',['Dims',['../structtflite_1_1_dims.html',1,'tflite']]],
  ['divoptionsbuilder_211',['DivOptionsBuilder',['../structtflite_1_1_div_options_builder.html',1,'tflite']]],
  ['divoptionst_212',['DivOptionsT',['../structtflite_1_1_div_options_t.html',1,'tflite']]],
  ['dmahardwarevtbl_213',['DMAHardwareVtbl',['../struct_d_m_a_hardware_vtbl.html',1,'']]]
];
